name: Push to S3

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ASIAQE3ROIZUTGI6SSMU
          aws-secret-access-key: K8Bk2liHspPVIXT6NSpWI8mNLQytptKlduGsXJ0k
          aws-region: us-east-1
      - name: Sync files to S3 bucket
        run: |
          aws s3 sync build s3://workbench-github-test --delete
